import "@/styles/embla.css";
import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { auth } from "@/server/auth";
import NextAuthProvider from "@/components/HOC/NextAuthProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  return (
    <html lang="en" className={`${geist.variable}`}>
      <NextAuthProvider session={session}>
        <body>{children}</body>
      </NextAuthProvider>
    </html>
  );
}
